update to elasticsearch 0.90.12

diff --git a/vendor/elasticsearch/bin/elasticsearch b/vendor/elasticsearch/bin/elasticsearch
--- a/vendor/elasticsearch/bin/elasticsearch
+++ b/vendor/elasticsearch/bin/elasticsearch
@@ -46,6 +46,20 @@
 # Be aware that you will be entirely responsible for populating the needed
 # environment variables.
 
+
+# Maven will replace the project.name with elasticsearch below. If that
+# hasn't been done, we assume that this is not a packaged version and the
+# user has forgotten to run Maven to create a package.
+IS_PACKAGED_VERSION='elasticsearch'
+if [ "$IS_PACKAGED_VERSION" != "elasticsearch" ]; then
+    cat >&2 << EOF
+Error: You must build the project with Maven or download a pre-built package
+before you can run Elasticsearch. See 'Building from Source' in README.textile
+or visit http://www.elasticsearch.org/download to get a pre-built package.
+EOF
+    exit 1
+fi
+
 CDPATH=""
 SCRIPT="$0"
 
@@ -75,7 +89,7 @@ if [ "x$ES_INCLUDE" = "x" ]; then
                    /usr/local/share/elasticsearch/elasticsearch.in.sh \
                    /opt/elasticsearch/elasticsearch.in.sh \
                    ~/.elasticsearch.in.sh \
-                   `dirname "$0"`/elasticsearch.in.sh; do
+                   "`dirname "$0"`"/elasticsearch.in.sh; do
         if [ -r "$include" ]; then
             . "$include"
             break
@@ -89,7 +103,12 @@ fi
 if [ -x "$JAVA_HOME/bin/java" ]; then
     JAVA="$JAVA_HOME/bin/java"
 else
-    JAVA=java
+    JAVA=`which java`
+fi
+
+if [ ! -x "$JAVA" ]; then
+    echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+    exit 1
 fi
 
 if [ -z "$ES_CLASSPATH" ]; then
@@ -121,16 +140,14 @@ launch_service()
         es_parms="$es_parms -Des.foreground=yes"
         exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props \
                 org.elasticsearch.bootstrap.ElasticSearch
-        execval=$?
+        # exec without running it in the background, makes it replace this shell, we'll never get here...
+        # no need to return something
     else
         # Startup ElasticSearch, background it, and write the pid.
         exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props \
                     org.elasticsearch.bootstrap.ElasticSearch <&- &
-        execval=$?
-        [ ! -z "$pidpath" ] && printf '%d' $! > "$pidpath"
+        return $?
     fi
-
-    return $execval
 }
 
 # Parse any command line options.
@@ -169,7 +186,7 @@ while true; do
             break
         ;;
         *)
-            echo "Error parsing arguments!" >&2
+            echo "Error parsing argument $1!" >&2
             exit 1
         ;;
     esac
